// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AppControllerGetHelloResponse } from './types.gen';

/**
 * @returns unknown
 * @throws ApiError
 */
export const appControllerGetHello = (): CancelablePromise<AppControllerGetHelloResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/'
}); };